### ISSUE TITLE
Autogain stays in endless loop with high light level

### ISSUE THREAD

**Issue by EvertDekker** [joba-1/Joba_Tsl2561#5]
When the sensor gets very high light level (direct sunlight) it will loops forever in the **bool autoGain**  sub.

Did some debugging myself, but can't find the solution.

The problem is in this part of the code (I think):
`    if( (full < 1000 && ++curr < sizeof(sensitivity)/sizeof(sensitivity[0])) || (full > limit && curr-- > 0) ) {
      if( !tsl.setSensitivity(sensitivity[curr].gain, sensitivity[curr].exposure) ) {
        return false; 
      }
      gain = sensitivity[curr].gain;
      exposure = sensitivity[curr].exposure;
      }
    else {
       if( ++curr > 0 && retryOnSaturated-- == 0 ) {
         return true; // saturated, but best we can do
      }
    }`

With high light level the first **if** is not true, code will then jump to the **else**, the **if** here is also not true and the code will jump to the begin of the sub and starts over. There will no false returned.

Added some debugging in front of this part code.
`Serial.printf("full=%u, curr=%u, limit=%u, sizeof=%u \n",  full, curr, limit, sizeof(sensitivity)/sizeof(sensitivity[0]));`
And that will print **full=5047, curr=0, limit=3783, sizeof=6**

If you need more data let me know.

**Comment by joba-1** [comment]
>
> Hi Evert,
>

I will look into it, thanks.
Please let me know should you find something more.

Do you mean, the code is stuck only until it gets darker, or once stuck it
stays that way?


-- 
iphone so i typo

**Comment by EvertDekker** [comment]
It get stuck until it gets darker.
Tip: I can simulate the direct sunlight by putting the led light of my phone direct on the sensor.

Btw running it on a ESP8266

**Comment by joba-1** [comment]
I think the last && should be an || instead.
Could you please try?

**Comment by EvertDekker** [comment]
Change the **&&** between **limit** and **curr** in an **||** doesn't help, make it only worse, now very low light levels are also not working.

**Comment by joba-1** [comment]
sorry, seems I need more info then to get it.
Just from looking at the code, it should not do this :)

The intention at the start of this code section is to adjust sensitivity (reduce curr if above zero and light is too bright or increase it if below 5 while light is too dark) and exit otherwise in the else clause because we are already at the sensitivity limits. The if in the else is just there to do some repeats at brightest light, because my sensors sometimes reported bright light up to ~3 times in a row although it actually was much darker.

As a workaround you could just return true in the else clause.

Interesting would be curr and retryOnSaturated at the beginning of the else block in addition to your print.

**Comment by EvertDekker** [comment]
Hi,
Thanks for your time and effort.
Here's some more debug info:

Starting Tsl2561Util autogain loop           <--Normal light condition
full=4, curr=3, limit=49149, sizeof=6 
full=12, curr=4, limit=27882, sizeof=6 
full=65, curr=5, limit=49149, sizeof=6 
curr=6, retryOnSaturated=10 
full=65, curr=7, limit=49149, sizeof=6 
curr=8, retryOnSaturated=9 
full=65, curr=9, limit=49149, sizeof=6 
curr=10, retryOnSaturated=8 
full=65, curr=11, limit=49149, sizeof=6 
curr=12, retryOnSaturated=7 
full=66, curr=13, limit=49149, sizeof=6 
curr=14, retryOnSaturated=6 
full=65, curr=15, limit=49149, sizeof=6 
curr=16, retryOnSaturated=5 
full=64, curr=17, limit=49149, sizeof=6 
curr=18, retryOnSaturated=4 
full=79, curr=19, limit=49149, sizeof=6 
curr=20, retryOnSaturated=3 
full=64, curr=21, limit=49149, sizeof=6 
curr=22, retryOnSaturated=2 
full=64, curr=23, limit=49149, sizeof=6 
curr=24, retryOnSaturated=1 
full=64, curr=25, limit=49149, sizeof=6 
curr=26, retryOnSaturated=0 
Back in main loop

full=77, curr=5, limit=49149, sizeof=6 
curr=6, retryOnSaturated=10 
full=62, curr=7, limit=49149, sizeof=6 
curr=8, retryOnSaturated=9 
full=62, curr=9, limit=49149, sizeof=6 
curr=10, retryOnSaturated=8 
full=61, curr=11, limit=49149, sizeof=6 
curr=12, retryOnSaturated=7 
full=61, curr=13, limit=49149, sizeof=6 
curr=14, retryOnSaturated=6 
full=61, curr=15, limit=49149, sizeof=6 
curr=16, retryOnSaturated=5 
full=61, curr=17, limit=49149, sizeof=6 
curr=18, retryOnSaturated=4 
full=61, curr=19, limit=49149, sizeof=6 
curr=20, retryOnSaturated=3 
full=61, curr=21, limit=49149, sizeof=6 
curr=22, retryOnSaturated=2 
full=60, curr=23, limit=49149, sizeof=6 
curr=24, retryOnSaturated=1 
full=60, curr=25, limit=49149, sizeof=6 
curr=26, retryOnSaturated=0 
Back in main loop

full=96, curr=5, limit=49149, sizeof=6 
curr=6, retryOnSaturated=10 
full=65535, curr=7, limit=49149, sizeof=6    <--High light condition
full=65535, curr=6, limit=3783, sizeof=6 
full=65535, curr=5, limit=49149, sizeof=6 
full=65535, curr=4, limit=27882, sizeof=6 
full=65535, curr=3, limit=49149, sizeof=6 
full=65535, curr=2, limit=3783, sizeof=6 
full=65535, curr=1, limit=27882, sizeof=6 
full=65535, curr=0, limit=3783, sizeof=6                <--Endless loop starts here
curr=255, retryOnSaturated=9 
full=65535, curr=0, limit=3783, sizeof=6 
curr=255, retryOnSaturated=9 
full=65535, curr=0, limit=3783, sizeof=6 
curr=255, retryOnSaturated=9 
full=65535, curr=0, limit=3783, sizeof=6 
curr=255, retryOnSaturated=9 



full=65535, curr=0, limit=3783, sizeof=6 
curr=255, retryOnSaturated=9 
full=5047, curr=0, limit=3783, sizeof=6 
curr=255, retryOnSaturated=9 
full=5047, curr=0, limit=3783, sizeof=6 
curr=255, retryOnSaturated=9 
full=5047, curr=0, limit=3783, sizeof=6 
curr=255, retryOnSaturated=9 
.
.
.
.

**Comment by EvertDekker** [comment]
Found it:

if( ++curr > 0 && retryOnSaturated-- == 0 )
Should be
if( curr++ > 0 && retryOnSaturated-- == 0 )

Tested it with low, medium and high light level, works fine.
Will throw now an error with very high light level

Thanks for pointing me in the right direction.

**Comment by joba-1** [comment]
Thanks for testing.

My intention was not throwing an error, but just returning the max light
level in that case.

curr++ will always be true: either it is 6 or 255. You could just delete it
and have the same effect.

When the first if() evaluates to false because light is too bright, the
last thing it does before going to the else block is change curr from 0 to
255.

In the else block this is corrected back to 0 before checking it is > 0.
I want to exit if it is bright (curr==0) and we have retried 10 times
(retryOnSaturated==0) or if it is dark (curr==6). I still think, this
paragraph could be written as if(++curr > 0 || retryOnSaturated-- == 0)
return true

I need to see this in action, I guess.


-- 
iphone so i typo

**Comment by joba-1** [comment]
I experimented with the issue-5 branch (it is difficult to interpret log output if you dont know the code that produces it).

My if(++curr > 0 || retryOnSaturated-- == 0) seems to behave as I want/expected:

* return immediate result if measured level is in a sane range
* adjust gain and exposure in max 5 steps to get the result in a sane range
* If at chip limit and still too dark, return result, if still too bright, retry up to 10 times before returning result (because my chips sporadically report full brightness whilt it is much darker).

I experienced no hangs at the limits very dark and super bright with that code.

Please retry with that branch and post the log output of a hang situation (preferrably in code tags) if it still occurres for you (different chips can behave differently...).

**Comment by EvertDekker** [comment]
Seems to work fine for me now, thanks.

**Comment by joba-1** [comment]
great!

Then I‘ll release a new version soon.
-- 
iphone so i typo

**Comment by mike2nl** [comment]
@joba-1 
Hi all,
i came over from tasmota on githib to see about another issue.
But saw that one here and had sometimes the same posted happening.

Question:
i tested now the changes in the latest tasmota (github) and it looks like that this issue here
is solved then. Much better dark values and no high ones.

For the test i got the issue5 brunch and commented out all the sprintf parts because we need
the serial interface for other things ;-).

About that your PR for this is still open (not merged) the question can you merged it now?
Because we wish use stable lib's only so no testing versions at all. 

Thanks for your time.

**Comment by joba-1** [comment]
Hi @mike2nl ,
the pr #6 is only for my testing (left there in case there are more problems with slow sensors). I don't intend to merge it in main code. V 2.0.7 is current and since there were no complaints about bogous readings since 6 months, I guess we are now waiting long enough even for the slowest chips out there -> stable enough for you?

**Comment by joba-1** [comment]
sorry @mike2nl , mixed that up with another change. This is still open and since the tests showed no issues to remind me, I forgot about it... My tasmota devices run fine with this, so I will merge it, but without the heavy serial output. Would that be ok for what you need?

**Comment by joba-1** [comment]
FWIW: this is in 2.0.8 now (and some better handling of full saturation in 2.0.9...)
